version: 2
updates:
  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      cli-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      web-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
